### ISSUE TITLE
missing train.py

### ISSUE THREAD

**Issue by Kevin7720** [chengyi-chris/UPure#1]
To replicate the proposed method, the following command needs to be executed as mentioned in [link](https://github.com/chengyi-chris/UPure?tab=readme-ov-file#please-execute-the-following-commands-to-replicate-our-method):
```
python train.py --c config/usb_cv/fixmatch/fixmatch_cifar10_100_0-defense.yaml
```
However, we couldn't find the `train.py` file. Therefore, providing the file would be a great help to our issues.

Thanks!

**Comment by chengyi-chris** [comment]
Hello, our code is based on the repo [Semi-Supervised Learning branchmark](https://github.com/microsoft/Semi-supervised-learning), we do not revise the code of `train.py`. We also upload `train.py`.
